version: "2"

linters:
  default: standard
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

  exclusions:
    warn-unused: true
    generated: strict
    paths:
      - ".*\\.gen\\.go$"

run:
  timeout: 1m
  allow-parallel-runners: true
  allow-serial-runners: true

output:
  show-stats: true
  formats:
    text:
      path: stdout

severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: info